### ISSUE TITLE
TwilioX needs LIBCURL.VCX; where can it be downloaded?

### ISSUE THREAD

**Issue by kennethtamayo** [VFPX/TwilioX#1]
TwilioX needs LIBCURL.VCX; where can it be downloaded?

**Comment by paladintodd** [comment]
The are at: http://curl.haxx.se/download.html 

I've also added LibCurl.zip to the project which contains the needed files as well.

**Comment by kennethtamayo** [comment]
Thank you Todd..!!!!

This made it work perfectly.
